[2023-12-08T22:47:20.620+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_processing_and_cleaning.save_data_task manual__2023-12-08T22:46:47.471557+00:00 [queued]>
[2023-12-08T22:47:20.629+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_processing_and_cleaning.save_data_task manual__2023-12-08T22:46:47.471557+00:00 [queued]>
[2023-12-08T22:47:20.629+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-12-08T22:47:20.640+0000] {taskinstance.py:1382} INFO - Executing <Task(_PythonDecoratedOperator): save_data_task> on 2023-12-08 22:46:47.471557+00:00
[2023-12-08T22:47:20.647+0000] {standard_task_runner.py:57} INFO - Started process 296 to run task
[2023-12-08T22:47:20.649+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'data_processing_and_cleaning', 'save_data_task', 'manual__2023-12-08T22:46:47.471557+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/data_processing_cleaning.py', '--cfg-path', '/tmp/tmpcb3f0q7z']
[2023-12-08T22:47:20.651+0000] {standard_task_runner.py:85} INFO - Job 16: Subtask save_data_task
[2023-12-08T22:47:20.664+0000] {logging_mixin.py:154} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2023-12-08T22:47:20.693+0000] {task_command.py:416} INFO - Running <TaskInstance: data_processing_and_cleaning.save_data_task manual__2023-12-08T22:46:47.471557+00:00 [running]> on host cd2a9dc484d2
[2023-12-08T22:47:20.780+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_processing_and_cleaning' AIRFLOW_CTX_TASK_ID='save_data_task' AIRFLOW_CTX_EXECUTION_DATE='2023-12-08T22:46:47.471557+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-08T22:46:47.471557+00:00'
[2023-12-08T22:47:20.781+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-12-08T22:47:20.788+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=data_processing_and_cleaning, task_id=save_data_task, execution_date=20231208T224647, start_date=20231208T224720, end_date=20231208T224720
[2023-12-08T22:47:20.821+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-12-08T22:47:20.837+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
